# Generated by Django 5.2 on 2025-04-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='college',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='college',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='college',
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.RemoveField(
            model_name='hostelfacility',
            name='college',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='college',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='college',
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
