# Generated by Django 5.1.6 on 2025-04-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatbot_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='chatbot_response',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='user_query',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='intent',
        ),
    ]
