# Generated by Django 5.1.6 on 2025-04-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_chatbot_response_chatbot_query_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='query',
            new_name='chatbot_response',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='response',
            new_name='user_query',
        ),
    ]
