# Generated by Django 5.1.6 on 2025-04-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_query_chatbot_chatbot_response_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chatbot',
        ),
    ]
