# Generated by Django 5.1.6 on 2025-04-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
