# Generated by Django 5.1.6 on 2025-04-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_chathistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiondetail',
            name='cutoff_rank',
        ),
    ]
