# Generated by Django 5.1.6 on 2025-05-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
